### ISSUE TITLE
Optimus: Change dependabot to run daily not weekly

### ISSUE THREAD

**Issue by EdwardPrentice** [AmigoAppAI/open-gpt#6]

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710850041563
‎
Update the Dependabot configuration to trigger dependency updates on a daily basis instead of weekly.
‎
https://github.com/AmigoAppAI/open-gpt/pull/7

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710850854088
‎
Change the schedule interval for the Dependabot configuration from weekly to daily.
‎
https://github.com/AmigoAppAI/open-gpt/pull/10

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710858462260
‎
Change the dependabot configuration to run daily instead of weekly for NPM package updates.
‎
https://github.com/AmigoAppAI/open-gpt/pull/11

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710858478435
‎
Change the update schedule for Dependabot in the Dependabot configuration file from weekly to daily.
‎
https://github.com/AmigoAppAI/open-gpt/pull/12

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710860887097
‎
Change the Dependabot configuration to schedule dependency updates on a daily basis instead of weekly.
‎
https://github.com/AmigoAppAI/open-gpt/pull/13

**Comment by Optimus-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710861039441
‎
Change the Dependabot configuration to run daily instead of weekly.
‎
https://github.com/AmigoAppAI/open-gpt/pull/14

**Comment by Amigo-The-Developer** [comment]
I've tried opening a PR to address this issue!
‎
optimus-change-dependabot-to-run-daily-not-weekly-1710864046032
‎
Change the Dependabot configuration to schedule updates on a daily basis instead of weekly.
‎
https://github.com/AmigoAppAI/open-gpt/pull/17
